name: os_fft
description: OS FFT
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  fftea:
    path:
      ../../../fftea
  protobuf: ^2.1.0
  wav: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.0.0
